Repository kijani-project/kijani-rest-api, pull requests merged in 2022-05, with the labels that each got.

#13 fixed merge conflicts
  src/main/java/com/kijani/restapi/data/DataMapper.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/resources/application.properties
Labels: bug-fix, new-feature

#15 Format code
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/model/Ecolabel.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/Supplier.java
Labels: enhancement

#18 Backend
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/data/DataMapper.java
  src/main/java/com/kijani/restapi/model/Category.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/repository/CategoryRepository.java
  src/main/java/com/kijani/restapi/repository/ProductRepository.java
  src/main/java/com/kijani/restapi/repository/SubCategoryRepository.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
  src/test/java/com/kijani/restapi/repository/ProductRepositoryTest.java
Labels: enhancement, new-feature

#17 Documentation endpoints
  README.md
Labels: enhancement

#19 Category and sub category
  src/main/java/com/kijani/restapi/controller/CategoryController.java
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/data/DataMapper.java
  src/main/java/com/kijani/restapi/model/Category.java
  src/main/java/com/kijani/restapi/model/Ecolabel.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/CategoryService.java
  src/main/java/com/kijani/restapi/service/impl/CategoryServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement, new-feature

#20 Category and sub category
  Docs/Payloads/Postman commands/Products/Kijani Product.postman_collection.json
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
Labels: enhancement, new-feature

#21 fixed infinite loop
  src/main/java/com/kijani/restapi/model/Ecolabel.java
  src/main/java/com/kijani/restapi/model/Product.java
Labels: bug-fix

#22 Add REST API documentaion
  README.md
Labels: enhancement

#23 changed endpoints to reflect documentation
  src/main/java/com/kijani/restapi/controller/CategoryController.java
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/controller/SupplierController.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/repository/ProductRepository.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/CategoryService.java
  src/main/java/com/kijani/restapi/service/impl/CategoryServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/SupplierService.java
  src/main/java/com/kijani/restapi/service/impl/SupplierServiceImpl.java
Labels: enhancement, new-feature

#24 Postman docs
  Docs/Payloads/Postman commands/Products/Kijani Product.postman_collection.json
  docs/postman/postman.json
Labels: enhancement, bug-fix

#25 Finish documentation
  src/main/java/com/kijani/restapi/controller/CategoryController.java
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/controller/SupplierController.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/SupplierService.java
  src/main/java/com/kijani/restapi/service/impl/SupplierServiceImpl.java
Labels: bug-fix

#26 CategoryController and SubCategoryController done look at TODO
  src/main/java/com/kijani/restapi/controller/CategoryController.java
  src/main/java/com/kijani/restapi/controller/SubCategoryController.java
  src/main/java/com/kijani/restapi/model/Category.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/java/com/kijani/restapi/repository/SubCategoryRepository.java
  src/main/java/com/kijani/restapi/service/impl/CategoryService.java
  src/main/java/com/kijani/restapi/service/impl/CategoryServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/SubCategoryService.java
  src/main/java/com/kijani/restapi/service/impl/SubCategoryServiceImpl.java
Labels: enhancement, new-feature

#29 Image attribute added to category
  src/main/java/com/kijani/restapi/model/Category.java
Labels: new-feature

#30 Database
  src/main/java/com/kijani/restapi/data/DataMapper.java
  src/main/java/com/kijani/restapi/model/Measurement.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/resources/application.properties
Labels: enhancement

#31 New endpoint for Products
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/data/DataMapper.java
  src/main/java/com/kijani/restapi/model/Category.java
  src/main/java/com/kijani/restapi/model/Measurement.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/java/com/kijani/restapi/repository/CategoryRepository.java
  src/main/java/com/kijani/restapi/repository/ProductRepository.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement, new-feature

#32 ManyToMany relations and new tables
  src/main/java/com/kijani/restapi/data/DataMapper.java
  src/main/java/com/kijani/restapi/model/EcoTest.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/ProductEcoLabel.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/model/SupplierEcoLabel.java
  src/main/java/com/kijani/restapi/repository/EcolabelRepository.java
Labels: enhancement, new-feature

#33 bug solved for creating product
  src/main/java/com/kijani/restapi/model/Category.java
  src/main/java/com/kijani/restapi/model/EcoTest.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/ProductEcoLabel.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/model/SupplierEcoLabel.java
Labels: bug-fix

#34 minor enchancement combined two endpoints
  src/main/java/com/kijani/restapi/controller/ProductController.java
Labels: enhancement

#35 New shell script with products
  src/main/resources/static/data/kijani.sh
Labels: new-feature

#37 Fix subcategory endpoint
  README.md
  src/main/resources/application.properties
Labels: bug-fix

#40 Product ecolabel endpoints CRUD
  README.md
  src/main/java/com/kijani/restapi/controller/ProductEcoLabelController.java
  src/main/java/com/kijani/restapi/controller/SupplierController.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/java/com/kijani/restapi/repository/ProductEcolabelRepository.java
  src/main/java/com/kijani/restapi/service/impl/ProductEcolabelService.java
  src/main/java/com/kijani/restapi/service/impl/ProductEcolabelServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/kijani/restapi/service/.keep
Labels: new-feature

#43 added postman Data Script
  docker-compose.yml
  docs/postman/SERVER CREATE  test data.postman_collection.json
Labels: enhancement

#44 Refactor
  README.md
  docs/postman/Create test data.postman_collection.json
  docs/postman/SERVER CREATE  test data.postman_collection.json
  docs/postman/kijani REST API.postman_collection.json
  src/main/java/com/kijani/restapi/controller/CategoryController.java
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/controller/ProductEcoLabelController.java
  src/main/java/com/kijani/restapi/controller/SubCategoryController.java
  src/main/java/com/kijani/restapi/controller/SupplierController.java
  src/main/java/com/kijani/restapi/model/EcoTest.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/ProductEcoLabel.java
  src/main/java/com/kijani/restapi/model/Role.java
  src/main/java/com/kijani/restapi/model/Supplier.java
  src/main/java/com/kijani/restapi/model/SupplierEcoLabel.java
  src/main/java/com/kijani/restapi/model/User.java
  src/main/java/com/kijani/restapi/repository/ProductEcoLabelRepository.java
  src/main/java/com/kijani/restapi/repository/ProductEcolabelRepository.java
  src/main/java/com/kijani/restapi/repository/ProductRepository.java
  src/main/java/com/kijani/restapi/repository/UserRepository.java
  src/main/java/com/kijani/restapi/service/CategoryService.java
  src/main/java/com/kijani/restapi/service/ProductEcoLabelService.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/SubCategoryService.java
  src/main/java/com/kijani/restapi/service/SupplierService.java
  src/main/java/com/kijani/restapi/service/impl/CategoryServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/ProductEcolabelService.java
  src/main/java/com/kijani/restapi/service/impl/ProductEcolabelServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/SubCategoryServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/SupplierService.java
  src/main/java/com/kijani/restapi/service/impl/SupplierServiceImpl.java
Labels: enhancement

#45 changes to data
  docs/postman/SERVER CREATE  test data.postman_collection.json
Labels: enhancement

#46 postman script fix.
  docs/postman/SERVER CREATE  test data.postman_collection.json
Labels: bug-fix

#47 Endpoint for getting products by Designer
  README.md
  docs/postman/SERVER CREATE  test data.postman_collection.json
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/ProductEcoLabel.java
  src/main/java/com/kijani/restapi/repository/ProductRepository.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
Labels: enhancement, new-feature

#48 fixed endpoint name
  src/main/java/com/kijani/restapi/controller/ProductController.java
Labels: bug-fix

#49 fixed bug required = false
  src/main/java/com/kijani/restapi/controller/ProductController.java
Labels: bug-fix

#52 new postman script
  docs/postman/SERVER CREATE  test data Copy.postman_collection.json
  docs/postman/SERVER CREATE  test data.postman_collection.json
Labels: enhancement

#53 Postman script updated
  docs/postman/SERVER CREATE test data.postman_collection.json
Labels: enhancement

#54 Not Null fix for measurement
  src/main/java/com/kijani/restapi/model/Measurement.java
Labels: bug-fix

#57 Breaking change - Designer ManyTOMany, postman updated, Readme updated
  README.md
  docs/postman/SERVER CREATE test data.postman_collection.json
  src/main/java/com/kijani/restapi/controller/DesignerController.java
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/model/Designer.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/repository/DesignerRepository.java
  src/main/java/com/kijani/restapi/repository/ProductRepository.java
  src/main/java/com/kijani/restapi/service/DesignerService.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/DesignerServiceImpl.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
Labels: enhancement, new-feature

#58 Fix infinity loop
  docs/postman/SERVER CREATE test data.postman_collection.json
  src/main/java/com/kijani/restapi/model/Designer.java
Labels: bug-fix

#59 Added custom Query for designer
  src/main/java/com/kijani/restapi/controller/DesignerController.java
  src/main/java/com/kijani/restapi/controller/ProductController.java
  src/main/java/com/kijani/restapi/repository/ProductRepository.java
  src/main/java/com/kijani/restapi/service/ProductService.java
  src/main/java/com/kijani/restapi/service/impl/ProductServiceImpl.java
Labels: bug-fix

#60 Postman update
  docs/postman/SERVER CREATE test data.postman_collection.json
Labels: bug-fix

#61 auto date and update in database plus fast refractor, postman updated
  docs/postman/SERVER CREATE test data.postman_collection.json
  src/main/java/com/kijani/restapi/model/Category.java
  src/main/java/com/kijani/restapi/model/EcoTest.java
  src/main/java/com/kijani/restapi/model/Product.java
  src/main/java/com/kijani/restapi/model/SubCategory.java
  src/main/java/com/kijani/restapi/service/impl/CategoryServiceImpl.java
Labels: enhancement, new-feature
